[package]
name = "java-properties"
version = "0.2.0"
authors = ["Adam Crume <adamcrume@gmail.com>"]
description = "A library for reading and writing Java properties files in Rust."
keywords = ["java", "properties"]
readme = "README.md"
repository = "https://github.com/adamcrume/java-properties"
license = "MIT"
documentation = "https://adamcrume.github.io/java-properties"

[dependencies]
encoding = "^0.2.32"
regex = "^0.1.47"
